version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
    networks:
      - webnet

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webnet
    depends_on:
      - web

networks:
  webnet:
