version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
    networks:
      - webnet
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt

networks:
  webnet:
